### ISSUE TITLE
Re-write the paragraph - CITROS Usage (SpycePy)

### ISSUE THREAD

**Issue by mariaBer** [lulav/citros_doc#68]
https://github.com/lulav/citros_doc/blob/95e99c3550bb5f2d65a653900cce697a4aaa17ae/docs_tutorials/spiceypy/spiceypy.md?plain=1#L30

Although you can get simulation results using FoxGlove, the best way to work with such simulations and process the results is CITROS! With its power, it is possible to create complex data processing scenarios, including the construction of more complex graphs, mathematical analysis and other high-level processing methods.

@vovacooper please add the explanation to @gtep96

**Comment by vovacooper** [comment]
@gtep96 

this paragraph need to be rewritten a little:
first of all Foxglove doesn't give you simulation results. it give you a way to replay your simulation and visualize them, there are no data analysis involved. 

the second part of this paragraph is good.
 
i would like to see some structure more like what issue you had that CITROS helped you to solve. 
what problem did you have that CITROS help you here with this project? 

for example for the cannon project, 
we can say that we can calculate the best angle of attack analytically, but if we assume that this is a very hard calculation (just for the example) and solve it by running Monte Carlo on the angle of attack, so we try thousands of different behaviour's, 
and the using the amazing data analysis tool from CITROS we can get the same result.

**Comment by vovacooper** [comment]
@gtep96 
i really liked this part:
The best way to work with such simulations and process the results is CITROS! With its power, it is possible to create complex data processing scenarios, including the construction of more complex graphs, mathematical analysis and other high-level processing methods.

can you please add some explanation about the data analysis part to

One of the main CITROS features is an ability to launch a number of simulations in parallel. For the projects like SpiceyPy example this feature allows user to simulate many different behaviours of the model regardless of the complexity of it and without restrictions on computing power."

**Comment by gtep96** [comment]
@vovacooper 

"The best way to work with such simulations and process the results is CITROS! With its power, it is possible to create complex data processing scenarios, including the construction of more complex graphs, mathematical analysis and other high-level processing methods.

One of the main CITROS features is an ability to launch a number of simulations in parallel. For the projects like SpiceyPy example this feature allows user to simulate many different behaviours of the model regardless of the complexity of it and without restrictions on computing power. Moreover, the amazing Data Analysis tool from CITROS allows user to process the simulation results with such useful packages as Error Analysis and Validation module"

**Comment by vovacooper** [comment]
@gtep96  much better. 
now we need to do it for all you tutorials as this paragraph is the same in all of them.

**Comment by gtep96** [comment]
done with #73

**Comment by mariaBer** [comment]
@gtep96, as I understand, @vovacooper's intention were re-write it to each tutorial and not copy word for word to othere tutorials, including "Spicepy" name

### Aero..
<img width="1363" alt="image" src="https://github.com/lulav/citros_doc/assets/23418333/4902884a-d3db-4650-9a0f-eb81e575de1d">

### Poliastro
<img width="1050" alt="image" src="https://github.com/lulav/citros_doc/assets/23418333/b73461fc-8c9b-4fac-a387-a827641aba0c">

### Turtlebot
<img width="1056" alt="image" src="https://github.com/lulav/citros_doc/assets/23418333/8844e40d-cccf-45b4-9029-068d1945d29b">

**Comment by vovacooper** [comment]
@gtep96 WTF? how spicyPy in all the projects?! 
please make the text for each project.

**Comment by gtep96** [comment]
@vovacooper @mariaBer Sorry for that, i've fixed the project's names and rewritten paragraphs for most of all tutorials. since the very meaning of this paragraph is to talk about the advantages of CITROS, and all my projects are very similar, I kept the general meaning, changing only the wording (using ChatGPT). The changes have been pushed already
