### ISSUE TITLE
Empty descriptions in section "CITROS Repository Directory and file structure"

### ISSUE THREAD

**Issue by kegly** [lulav/citros_doc#80]
In section CLI /  "CITROS Repository Directory and file structure"
Empty descriptions about directories: reports, notebooks

![photo_2023-11-21_19-59-11](https://github.com/lulav/citros_doc/assets/90460093/7720b07a-0f23-4686-a00f-9c43501fd189)
![photo_2023-11-21_19-59-09](https://github.com/lulav/citros_doc/assets/90460093/6a548a92-ba71-4010-a2f2-5994077d497a)

**Comment by mariaBer** [comment]
Done
