### ISSUE TITLE
General points to make better

### ISSUE THREAD

**Issue by meshiblum** [lulav/citros_doc#90]
1. Generally, there should be an emphasis on what citros does (help run many simulations and preform data analysis on them) and why you should use it. Only after reading much material from the documentation did I really realise what it does. I think it should be clear from the start, from the first landing page.
1. when we state docker as a requirement to use citros, we should state that the user should have: Docker installed on their computer, and preferably in VScode and should also have devcontainers as we will work inside them. (Here is a tutorial I wrote regarding this: 
 ## Docker
To start working with Docker, you should follow these simple steps:
1. Make sure you have VSCode on your computer, it is a convenient code editor and compiler with relevant extensions. Use the following link and choose the .deb extension: [VSCode Download](https://code.visualstudio.com/download)
2. In the extension of VSCode, download the Docker extension 
3. To actually use the Docker extension you have just installled in VScode, you'll need to install docker on your computer for your version of ubuntu.
Go to the following link and follow the instruction [Docker for Ubuntu download](https://docs.docker.com/engine/install/ubuntu/).\
Pay attention to:
* Usually you wont have to uninstall previous Docker versions, check if you have Docker on your computer using `Docker` command in the terminal. If the computer auto-completes (using tab before finishing the writing Docker) then you have some version of Docker, and will need to follow uninstall instructions.
* Make sure you follow the [postinstall](https://docs.docker.com/engine/install/linux-postinstall/) instructions as well. 
4. Install the [Dev Containers extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers).
)
##
1. Complete directory notebooks in https://citros.io/doc/docs_cli/structure/citros_structure 
1. Needs completion https://citros.io/doc/docs/quickstart/quick_tbd 
1. Edit readme https://github.com/citros-garden/pendulum 
1. In this github repository, the link is not working anymore https://github.com/citros-garden/aerosandbox_cessna 
![image](https://github.com/lulav/citros_doc/assets/96493950/9bd3761a-dd63-43ca-90c3-dff28e6a1e1e)
and There is a problem on this page with the tips (layout) 
1. This is wrong, the simulation runs 3 times in the previous step https://citros.io/doc/docs_tutorials#working-with-citros-cli---offline   
![image](https://github.com/lulav/citros_doc/assets/96493950/b02b4d18-e99f-4ee3-a98b-b21b16289cb9)

1. This is a bit misleading, you should have this note before the command  https://citros.io/doc/docs_tutorials#working-with-citros-cli---offline  
![image](https://github.com/lulav/citros_doc/assets/96493950/173e2ed8-fcbd-4fcf-8299-9e2f81f28bef)
1. Missing example for setup-ssh in the CLI page also in logout https://citros.io/doc/docs_cli/commands/cli_commands 
1. Maybe should emphasise generally in the website that you can use only the ROS first and then use CITROS to run it multiple times.. It is chronologically arranged that way in the document but I think this should be added as an explanation in the beginning of the document.

**Comment by mariaBer** [comment]
@meshiblum You added too much issues in one issue, split each one to a different issue
If you see multiple issues in a page, and you think are should bee fixed together, instead of numbering, use task list.
I'm closing this issue, re-open new ones so I could address them

**Comment by mariaBer** [comment]
@meshiblum I reopened it in case you didnt find it
