### ISSUE TITLE
General notes

### ISSUE THREAD

**Issue by meshiblum** [lulav/citros_doc#93]
1. Here, should be written "easy system integration" not easily.. also the capital letters are very random which does not look good
https://github.com/citros-garden 
![image](https://github.com/lulav/citros_doc/assets/96493950/4ee607cb-d81e-4771-9901-1f85aec2dc58)
2. I think this is a very good example as to what we should have for the CITROS website: https://naif.jpl.nasa.gov/naif/new_to_spice.html explaining what to expect and how you should start.

**Comment by mariaBer** [comment]
@meshiblum  It is iirrelevant to citros-doc, Re-open issue in [citros-garden](https://github.com/citros-garden/garden/issues).
assign Vova or Iftach
